//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewBoost.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckinTransaction
    {
        public System.Guid id { get; set; }
        public System.Guid providerId { get; set; }
        public System.Guid receiverId { get; set; }
    }
}
