//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewBoost.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Services = new HashSet<Service>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public string hoursOfOperation { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
    }
}
