//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewBoost.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.DonationTransactions = new HashSet<DonationTransaction>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<DonationTransaction> DonationTransactions { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
